version: 2
log-file: ./output.log
log-level: 1
root-markers:
  - .git/
lint-debounce: 1s
tools:
  eslint: &eslint
    lint-command: './node_modules/.bin/eslint -f unix --stdin'
    lint-ignore-exit-code: true
    lint-stdin: true

  mix_credo: &mix_credo
    lint-command: "MIX_ENV=test mix credo suggest --format=flycheck --read-from-stdin ${INPUT}"
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %t: %m'
      - '%f:%l: %t: %m'
    lint-category-map:
      R: N
      D: I
      F: E
      W: W
    lint-ignore-exit-code: true
    root-markers:
      - mix.lock
      - mix.exs
  
  mix_format: &mix_format
    format-command: "mix format --stdin-filename ${INPUT} -"
    format-stdin: true
    root-markers:
      - mix.lock
      - mix.exs
languages:
  javascript:
    - <<: *eslint
  typescript:
    - <<: *eslint
  elixir:
    - <<: *mix_format
    - <<: *mix_credo
